[workspace]

members = [
    "common",
    "syntax",
    "ono"
]

[workspace.dependencies]
logos = "0.13.x"
clap = { version = "4.1.8", features = ["derive"] }
codespan-reporting = "0.11.1"
unindent = "0.1"
termcolor = "1.1.3"
anyhow = "1.0.x"
